import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function FamilyManagerModal({ open, busyAction, profile, selectedGroupId, selectedGroup, marketsCount, joinCode, setJoinCode, referralJoinCode, selectedGroupInviteUrl, onClose, onSelectGroup, onJoinGroup, onCopyInviteLink, onRemoveMember, onDeleteGroup }) {
    if (!open) {
        return null;
    }
    return (_jsxs("section", { className: "settings-overlay", "aria-label": "Manage family", children: [_jsx("button", { className: "settings-backdrop", type: "button", "aria-label": "Close family manager", onClick: onClose }), _jsxs("article", { className: "panel settings-panel settings-modal family-manager-modal", children: [_jsxs("div", { className: "panel-heading settings-modal-heading", children: [_jsxs("div", { children: [_jsx("p", { className: "kicker", children: "Family manager" }), _jsx("h2", { children: selectedGroup?.name ?? "Manage your families" })] }), _jsx("button", { className: "toolbar-button toolbar-button-secondary", type: "button", onClick: onClose, children: "Close" })] }), _jsxs("div", { className: "family-manager-grid", children: [_jsxs("div", { className: "family-manager-column", children: [_jsxs("div", { className: "compact-form family-summary-card", children: [_jsx("strong", { children: selectedGroup?.name ?? "Choose a family group" }), _jsx("p", { className: "subtle-copy", children: selectedGroup
                                                    ? `Join code ${selectedGroup.joinCode}`
                                                    : "Create a group or join one with a code." }), _jsxs("div", { className: "family-strip-meta", children: [_jsxs("div", { className: "compact-metric", children: [_jsx("span", { className: "metric-label", children: "Members" }), _jsx("strong", { children: selectedGroup?.members.length ?? 0 })] }), _jsxs("div", { className: "compact-metric", children: [_jsx("span", { className: "metric-label", children: "Visible markets" }), _jsx("strong", { children: marketsCount })] })] })] }), _jsxs("div", { className: "compact-form", children: [_jsx("span", { className: "subtle-copy", children: "Switch family" }), _jsx("div", { className: "group-selector vertical", children: profile.groups.map((group) => (_jsxs("button", { type: "button", className: selectedGroupId === group.id ? "group-pill active" : "group-pill", onClick: () => onSelectGroup(group.id), children: [_jsx("span", { children: group.name }), _jsx("strong", { children: group.role }), _jsx("small", { children: group.joinCode })] }, group.id))) })] })] }), _jsxs("div", { className: "family-manager-column", children: [!referralJoinCode ? (_jsxs("form", { onSubmit: (event) => void onJoinGroup(event), className: "form-stack compact-form", children: [_jsx("span", { className: "subtle-copy", children: "Join another family group" }), _jsx("input", { value: joinCode, onChange: (event) => setJoinCode(event.target.value.toUpperCase()), placeholder: "Join code", required: true }), _jsx("button", { className: "ghost-button", type: "submit", disabled: busyAction === "join-group", children: "Join group" })] })) : null, selectedGroup ? (_jsxs("div", { className: "compact-form", children: [_jsx("strong", { className: "subtle-copy", children: "Invite people" }), _jsx("p", { className: "subtle-copy invite-link-copy", children: selectedGroupInviteUrl }), _jsx("button", { className: "ghost-button", type: "button", onClick: () => void onCopyInviteLink(selectedGroup.joinCode), children: "Copy invite link" })] })) : null, selectedGroup && selectedGroup.role === "ADMIN" ? (_jsxs("div", { className: "form-stack compact-form", children: [_jsx("span", { className: "subtle-copy", children: "Manage members" }), selectedGroup.members
                                                .filter((member) => member.id !== profile.user.id)
                                                .map((member) => (_jsxs("div", { className: "member-card member-management-row", children: [_jsxs("div", { children: [_jsx("strong", { children: member.displayName }), _jsx("span", { children: member.role })] }), _jsx("button", { className: "ghost-button", type: "button", disabled: busyAction === `remove-member-${member.id}`, onClick: () => void onRemoveMember(selectedGroup.id, member.id, member.displayName), children: "Remove" })] }, member.id))), _jsx("button", { className: "toolbar-button toolbar-button-secondary", type: "button", disabled: busyAction === `delete-group-${selectedGroup.id}`, onClick: () => void onDeleteGroup(selectedGroup.id, selectedGroup.name), children: "Delete family" })] })) : null] })] })] })] }));
}
